### ISSUE TITLE
Bot reacts to messages that start with mentions

### ISSUE THREAD

**Issue by IchSachErsmaMoin** [martijnmumbles/DomeTracker#1]
Example:
Message: "@User i am mentioning"
Yet Another Bot: "That command wasn't found! Try <help"

**Comment by martijnmumbles** [comment]
Discord uses the "<" character as part of it's syntax, such as "<@149112297355214849>". This overlapped with the prefix. Changing the prefix to "$" solves it for now.

A nice feature would be to allow the prefix to be set dynamically. There's some options for that, but seeming there's no one else using the bot there's no real use-case.
